# Bu araç @keyiflerolsun tarafından | @KekikAkademi için yazılmıştır.

name: PyPI Yükleyici

on:
  push:
    paths:
      - setup.py
  pull_request:
    paths:
      - setup.py

jobs:
  PyPIYukleyici:
    name    : PyPI Yükleyici
    runs-on : ubuntu-latest

    steps:
      - name: Depo Kontrolü
        uses: actions/checkout@v3

      - name: Python 3.10.8 Yükle
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.8"

      - name: Python Sürümünü Göster
        run : python -c "import sys; print(sys.version)"

      - name: Gereksinimleri Yükle
        run : |
          python -m pip install --upgrade pip
          pip install -U setuptools wheel build twine cibuildwheel

      - name: Kütüphaneyi PyPI'ye Yükle
        env :
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          CIBW_BUILD: cp38-* cp39-* cp310-* cp311-*
        run : |
          python -m build --sdist
          python -m cibuildwheel --output-dir dist;
          twine check dist/*
          python -m twine upload dist/*
          rm -rf build/ dist/ *.egg-info/